array1 =
  ["", "The Luscious", "Sonic", "Dylan's", "Killer", "Solar", "The Raw", "Suburban", "Legendary", "Return of The", "", "Atomic", "New Wave", "Bronx", "Harmonic", "Cuban", "Hot", "Last", "Total", "The Electric", "The Lost", "The Reno", "The Free", "Super", "Classic", "The Loose", "The Hip", "American", "The Nuclear", "Original", "The Vintage", "The Stone", "World Famous", "Satan's", "The Stray", "The Rolling", "The Satanic", "The Wild", "The Rogue", "First Rate", "Serious", "The Mighty", "West Street", "The Starski", "Sugarhill", "The Funky", "Positive", "The Heat-Seeking", "", "Eastern", "The Easy", "Beautiful", "A-List", "The Sinatra", "Dean's", "Cali", "Hotshot", "Original", "Hot", "Toxic", "Sunset", "", "Atomic", "Crystal", "Paris", "Supersonic", "Global", "Universal", "Primal", "Quadraphonic", "", "Chemical", "Holy", "Executive","Detroit", "Revenge of The", "Slick", "The Anti", "The Dark", "The Retro", "The Fabulous", "The Real", "The Freestyle", "Undercover", "New York", "Satin", "Attack of The", "Brooklyn", "Khaki", "The All-Seeing", "West Coast", "Super Heavy", "Premium", "Alcatraz", "Destiny's", "", "Cuban", "Vegas", "Intergalactic", "Manic", "Liquid", "Instant", "", "", "Flash", "NorThern", "SouThern", "Stone Cold", "Bristol", "Western", "Stealth", "Alabama", "Louisiana", "Camino", "Kamikaze", "The 100%", "The Sassy", "", "The True", "Travelling", "The Maniac", "Criminal", "Abandoned", "Virtuoso", "Lying", "Junior", "Latin", "Midnight", "Suburban", "Saxon", "Evil", "Sinister", "Idyllic", "Burnin'", "Texas", "National", "Giant", "The Lush", "California", "The Young", "The Psychedelic", "Rare", "Hyper", "Suprme", "The Great", "The Mean", "Eclectic"]

array2 =
  ["Disco", "", "", "Liberty", "Whiskey", "Culture", "Glitter", "Hollywood", "Manson", "Mood", "Beat", "Freedom", "Soho", "Rock", "Harmonic", "", "Candy", "Communication", "Social", "Pearl", "", "Sugar", "Karma", "Mambo", "Pimp", "Class", "Speed", "Funk", "Afro", "Glitz", "Soul", "Jazz", "Punk", "Leisure", "Folk", "Gravity", "", "Kitsch", "", "Freeze", "Paparazzi", "Love", "Science", "Vamp", "Nova", "Action", "Porn", "Super", "Monroe", "Presley", "Eastwood", "Vip", "Style", "Fashion", "Anger", "Sound", "Rebel", "Ninja", "Diamond", "Radio", "Electro", "", "Pressure", "Psycho", "", "Shadow", "Corrado", "Hipster", "Blues", "", "Lust", "Passion", "", "Polka", "Dancefloor", "Ghetto", "", "Voltage", "Truth", "Litmus", "Lunar", "Knowledge", "Fire", "Pop", "Lounge", "Sex", "Stereo", "Wonder", "Rhythm", "Bass", "Frat", "City", "Teen", "Glamour", "Uproar", "Thrill", "Devil", "Cream", "Casino", "Libra", "1-800", "Sitar", "Cherry", "Drama", "Shakedown", "Hi-Fi", "Dynamite"]

array3 =
  ["Kings", "Junkies", "Sultans", "Arrangement", "Orchestra", "Club", "Association", "Outcasts", "Idols", "Society", "Liberation", "Party", "Empire", "", "Club", "Society", "Freaks", "Club", "Project", "Legacy", "Pistols", "Assassins", "Connection", "Members", "", "Catalysts", "Experience", "", "Palace", "", "Seekers", "Missiles", "Massacre", "Icons", "Scene", "Cowboys", "Mafia", "Force", "Dolls", "Dictators", "Cheerleaders", "Fusion", "Band", "Heroes", "", "Poets", "All-Stars", "Section", "", "Queens", "Collective", "Group", "Hounds", "Pack", "Gods", "Geeks", "Gurus", "Giants", "Prophets", "Scandal", "", "Workshop", "Dream", "Precedent", "", "Legacy", "Dynasty", "Saviours", "Pimps", "", "Rockets", "Cavaliers", "Cats", "Freaks", "Lovers", "Club", "Demons", "Movement","Angels", "Explosion", "Team", "Machine", "Spectrum", "Voyage", "Eclipse", "Train", "Divas", "Kittens", "Destroyers", "123'S", "Survivors", "Cafe", "Wolverines", "Speakers", "Preachers", "Babes", "Code", "Players", "Army", "Blitz", "Invasion", "Cabaret", "Chiefs", "Clan", "Godess", "Pushers", "Feinds", "Wasteland", "Knights", "Police", "Oddysey", "Bomb", "Superstars", "Scene", "", "", "Group"]

module.exports = (robot) ->
  robot.respond /what is your favorite band/i, (msg) ->
    random_band = array1[Math.floor(Math.random() * array1.length)] + ' ' + array2[Math.floor(Math.random() * array2.length)] + ' ' + array3[Math.floor(Math.random() * array3.length)]
    msg.send random_band
